In [21]:
import pandas as pd
import numpy as np
import os

In [22]:
df_path = os.path.abspath("C:\\Users\\GRIZELLE\\GitHub Projects\\100-Days-Of-Coding-ML\\Datasets\\StackOverflow survey data\\survey_results_public.csv")

schema_df_path = os.path.abspath("C:\\Users\\GRIZELLE\\GitHub Projects\\100-Days-Of-Coding-ML\\Datasets\\StackOverflow survey data\\survey_results_schema.csv")

In [23]:
df = pd.read_csv(df_path, index_col='Respondent')
schema_df = pd.read_csv(schema_df_path, index_col='Column')

In [24]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [25]:
column_names = list(df.columns.values)
print(column_names)

['MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq', 'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc', 'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith', 'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors', 'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith', 'MiscTechDesireNextYear', 'MiscTechWorkedWith', 'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps', 'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch', 'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms', 'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites', 'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear', 'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount', 'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength', 'Trans', 'UndergradMajor', 'WebframeDesireNextYear', 'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode', 'YearsCodePro']

In [26]:
df[column_names].select_dtypes(int).describe()

ValueError: Cannot describe a DataFrame without columns

In [33]:
# Chaining
(
    df
    [column_names]
    .describe()
)

                Age      CompTotal  ConvertedComp   WorkWeekHrs
count  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean      30.834111  3.190464e+242   1.037561e+05     40.782174
std        9.585392            inf   2.268853e+05     17.816383
min        1.000000   0.000000e+00   0.000000e+00      1.000000
25%       24.000000   2.000000e+04   2.464800e+04     40.000000
50%       29.000000   6.300000e+04   5.404900e+04     40.000000
75%       35.000000   1.250000e+05   9.500000e+04     44.000000
max      279.000000  1.111111e+247   2.000000e+06    475.000000

In [27]:
# can comb08 be and int8
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [28]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [36]:
# Chaining
(
    df
    [column_names]
    .groupby('Country')
    .nunique()
)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,5,2,10,17,3,22,21,8,8,29,28,38,8,6,12,4,29,5,3,38,42,22,18,19,19,3,5,5,19,17,3,3,3,2,5,16,4,15,29,3,9,24,23,3,5,3,6,6,6,3,3,2,6,30,23,5,12,19,13
Albania,4,2,17,19,2,16,16,6,6,33,31,34,6,5,3,2,24,5,3,37,37,27,20,26,30,3,5,5,24,17,4,3,3,2,5,14,4,10,26,3,7,35,34,3,3,3,5,5,4,2,3,2,6,26,26,6,7,12,14
Algeria,5,2,24,17,3,14,15,4,4,53,46,37,8,6,9,3,40,5,3,66,66,50,30,41,28,3,5,5,29,23,4,3,3,2,5,21,4,16,48,4,8,61,47,3,2,3,6,5,5,3,3,1,10,54,43,6,13,17,13
Andorra,4,2,3,7,2,2,2,5,5,7,8,7,5,4,2,1,3,5,2,6,8,5,8,6,9,1,3,3,3,3,4,3,3,2,2,6,2,5,7,3,4,8,9,3,2,3,4,2,2,2,2,1,4,8,8,3,3,6,6
Angola,5,2,3,4,3,3,2,3,3,4,2,3,4,6,2,2,3,3,3,4,3,3,2,4,3,3,3,3,4,3,2,3,3,2,3,3,3,5,3,2,3,5,3,2,2,1,4,2,4,2,2,1,3,3,3,2,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Venezuela, Bolivarian Republic of...",4,2,21,17,3,24,25,3,3,49,43,46,8,5,12,3,35,5,3,55,55,48,25,36,33,3,4,5,36,23,4,3,3,2,5,16,4,9,38,3,7,54,42,3,4,3,6,6,5,3,3,1,7,50,47,6,17,25,20
Viet Nam,5,2,31,29,3,66,68,12,12,132,134,115,9,7,12,5,86,5,3,210,212,107,73,114,130,3,5,5,90,40,4,3,3,2,5,41,4,24,97,4,9,177,166,3,5,3,6,6,6,3,3,2,12,132,136,6,25,28,20
Yemen,2,2,2,4,1,1,1,1,1,7,5,3,3,4,2,1,3,2,3,7,6,5,5,4,4,2,2,2,2,2,2,2,1,1,2,5,3,3,6,1,2,7,6,2,1,1,1,1,2,2,1,1,3,6,5,2,1,5,2
Zambia,4,2,7,8,3,5,5,2,2,13,11,15,7,5,2,2,10,5,3,12,14,10,7,12,7,3,3,5,6,6,3,3,3,2,5,9,3,7,12,3,6,14,11,2,2,2,5,5,4,2,3,2,4,14,9,5,7,10,8
Zimbabwe,4,2,11,11,3,11,10,2,2,24,21,18,5,6,1,1,18,5,3,24,25,17,14,22,19,3,5,5,17,17,3,3,3,2,5,16,4,8,20,3,6,24,24,3,1,2,5,5,5,2,2,1,5,23,24,5,10,11,8